# Generated by Django 4.2.1 on 2023-06-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='total_balace_qty',
            new_name='total_balance_qty',
        ),
    ]
