# Generated by Django 4.2.1 on 2023-06-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
