# Generated by Django 4.2.1 on 2023-06-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customer_remove_sale_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '7. Customers'},
        ),
    ]
